---
- name: Generate the hosts file
  hosts: all
  become: true
  tasks:
    - name: Generate the file /etc/myhosts on dev host group
      template:
        src: host.j2
        dest: /etc/myhosts      
      when: inventory_hostname in groups['dev']
